# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.cache/wt [current_project]
set_property parent.project_path C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/sources_1/imports/cpe233/ALU_1/ALU_1.srcs/sources_1/imports/new/ALU.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/sources_1/new/ALU_MUX.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/sources_1/imports/cpe233/RAT5/ControlUnit/ControlUnit.srcs/sources_1/new/ControlUnit.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/sources_1/imports/cpe233/RAT2/RAT2/RAT2.srcs/sources_1/new/MUX24.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/sources_1/imports/cpe233/RAT2/RAT2/RAT2.srcs/sources_1/new/PC.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/sources_1/new/PC_and_MUX.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/sources_1/new/RAT_MCU.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/sources_1/new/REG_MUX.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/sources_1/new/Register_File.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/new/Scratch_DIN_MUX.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/new/Scratch_MUX.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/new/Scratch_RAM.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/new/Stack_Pointer.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/Downloads/counter_for_one_shot.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/cpe233/debounce_one_shot_FSM.vhd
  C:/Users/cfro/Documents/CPE_233/flags.vhd
  C:/Users/cfro/Documents/CPE_233/prog_rom.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/imports/new/sseg_dec.vhd
  C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/sources_1/new/RAT_WRAPPER.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/constrs_1/imports/Downloads/Basys3_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/cfro/Documents/CPE_233/RAT_8/RAT_8.srcs/constrs_1/imports/Downloads/Basys3_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top RAT_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RAT_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RAT_wrapper_utilization_synth.rpt -pb RAT_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
